# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions


export TOOLS_HOME=/tools

# OpenJDK
export JAVA_HOME=$TOOLS_HOME/jdk1.8.0_192

#export HADOOP_HOME=$TOOLS_HOME/hadoop-2.7.7
export HADOOP_HOME=$TOOLS_HOME/hadoop-3.1.1

export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop

export HADOOP_CLASSPATH=$JAVA_HOME/lib/tools.jar

export HIVE_HOME=$TOOLS_HOME/apache-hive-2.3.3-bin
export HIVE_CONF_DIR=$HIVE_HOME/conf

export ZOOKEEPER_HOME=$TOOLS_HOME/zookeeper-3.4.13

export KAFKA_HOME=$TOOLS_HOME/kafka_2.11-2.0.0

export HBASE_HOME=$TOOLS_HOME/hbase-2.1.0

export SPARK_HOME=$TOOLS_HOME/spark-2.3.1-bin-hadoop2.7
#export SPARK_HOME=$TOOLS_HOME/spark-2.4.0-bin-hadoop2.7
export SPARK_DIST_CLASSPATH=$($HADOOP_HOME/bin/hadoop classpath)

export PIG_HOME=$TOOLS_HOME/pig-0.17.0

export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH:$HADOOP_HOME/lib/native/:.

export SCALA_HOME=$TOOLS_HOME/scala-2.11.12

export KYLIN_HOME=$TOOLS_HOME/apache-kylin-2.6.2-bin-hbase1x

export PATH=.:$PATH:$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$HBASE_HOME/bin:$HIVE_HOME/bin:$SPARK_HOME/bin:$SPARK_HOME/sbin:$ZOOKEEPER_HOME/bin:$KAFKA_HOME/bin:$SCALA_HOME/bin:$KYLIN_HOME/bin

export CLASSPATH=.:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar

export JSVC_HOME=$TOOLS_HOME/commons-daemon-1.1.0-native/unix
# hadoop-3.1.1
export HDFS_DATANODE_SECURE_USER=root
export HDFS_NAMENODE_USER=root
export HDFS_SECONDARYNAMENODE_USER=root
export YARN_RESOURCEMANAGER_USER=root
export YARN_NODEMANAGER_USER=root

echo `hostname` /root/.bashrc
