# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

# OpenJDK
export JAVA_HOME=/tools/jdk1.8.0_192

#export HADOOP_HOME=/tools/hadoop-2.7.7
export HADOOP_HOME=/tools/hadoop-3.1.1

export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop

export HADOOP_CLASSPATH=$JAVA_HOME/lib/tools.jar

export HIVE_HOME=/tools/apache-hive-2.3.3-bin
export HIVE_CONF_DIR=$HIVE_HOME/conf

export ZOOKEEPER_HOME=/tools/zookeeper-3.4.13

export KAFKA_HOME=/tools/kafka_2.11-2.0.0

export HBASE_HOME=/tools/hbase-2.1.0

#export SPARK_HOME=/tools/spark-2.3.1-bin-hadoop2.7
export SPARK_HOME=/tools/spark-2.3.2-bin-without-hadoop

export PIG_HOME=/tools/pig-0.17.0

export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH:$HADOOP_HOME/lib/native/:.

export PATH=.:$PATH:$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$HBASE_HOME/bin:$HIVE_HOME/bin:$SPARK_HOME/bin:$SPARK_HOME/sbin:$ZOOKEEPER_HOME/bin:$KAFKA_HOME/bin

export CLASSPATH=.:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar

# hadoop-3.1.1
export HDFS_DATANODE_SECURE_USER=root
export HDFS_NAMENODE_USER=root
export HDFS_SECONDARYNAMENODE_USER=root
export YARN_RESOURCEMANAGER_USER=root
export YARN_NODEMANAGER_USER=root

echo `hostname` /root/.bashrc
